//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extractor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Extractor.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extraction. File has estimated {0} frames. Applying drop ratio of {1}. Final frame count: {2}..
        /// </summary>
        internal static string Begin_Extraction {
            get {
                return ResourceManager.GetString("Begin_Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop ratio must be between 0 and 1.
        /// </summary>
        internal static string DropRatioRequirements {
            get {
                return ResourceManager.GetString("DropRatioRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist....
        /// </summary>
        internal static string File_Does_Not_Exist {
            get {
                return ResourceManager.GetString("File_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of frames: {0}, Frame Size: {1}, is Variable FR: {2}, Avg. FR: {3}.
        /// </summary>
        internal static string InfoLine1 {
            get {
                return ResourceManager.GetString("InfoLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation: {0}, is Interlaced: {1}, Pixel Format {2}, Duration: {3}, Codec: {4}.
        /// </summary>
        internal static string InfoLine2 {
            get {
                return ResourceManager.GetString("InfoLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata: .
        /// </summary>
        internal static string MetadataHeader {
            get {
                return ResourceManager.GetString("MetadataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1};.
        /// </summary>
        internal static string MetadataPair {
            get {
                return ResourceManager.GetString("MetadataPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headroom must be between 0 and 1..
        /// </summary>
        internal static string NormalizeLuminanceCommandHandler_NormalizeImageExposure_Headroom_must_be_between_0_and_1_ {
            get {
                return ResourceManager.GetString("NormalizeLuminanceCommandHandler_NormalizeImageExposure_Headroom_must_be_between_" +
                        "0_and_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing frame {0} of {1}. {2:0} seconds elapsed of estimated {3:0} seconds. {4:0} seconds remaining..
        /// </summary>
        internal static string ProcessingFrame {
            get {
                return ResourceManager.GetString("ProcessingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task complete in {0:0.00} seconds.
        /// </summary>
        internal static string TaskCompleteText {
            get {
                return ResourceManager.GetString("TaskCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on IO to save {0} files. Runtime: {1:0}.
        /// </summary>
        internal static string WaitingIOSave {
            get {
                return ResourceManager.GetString("WaitingIOSave", resourceCulture);
            }
        }
    }
}
